---
title: 'Reliability, Maintainability, and Quality Management'
subtitle: 'LOGM 634 (ASAM - Winter 2016)'
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Professor

Maj Jason K. Freels, PhD 	<jason.freels@us.af.mil>\newline\newline
AFIT/ENV\newline
2950 Hobson Way\newline
WPAFB, OH 45433-7765\newline
Cell:  937.430.6619\newline
Work:  937.255.3636 ext 4676	  	
			
## Course Text

- Ebeling, C., <u>__An Introduction to Reliability and Maintainability Engineering__</u>, 2nd Ed., Waveland Press, 2010

## Additional References (Optional)

- O'Connor, P. & Kleyner, A., <u>__Practical Reliability Engineering__</u>, 5th Ed., Wiley, 2012

- Meeker, W. & Escobar, L., <u>__Statistical Methods for Reliability Data__</u>, 1st Ed., Wiley, 1998

- Rausand, M. & Hoyland, A., <u>__Systems Reliability Theory – Statistical Methods and Applications__</u>, 2nd Ed., Wiley, 2003

- DOD Guide for Achieving Reliability, Availability, and Maintainability, 3 Aug 2005

## Course Description

Creating and sustaining military capability is the purpose of military leadership and management. Reliability and maintainability (R&M) are component characteristics, which define the ability of a product to perform its specified functions throughout its operational life. Component R&M of the military system are primary determinants of military capability. This course teaches fundamental R&M concepts. Additionally, probability theory is discussed and employed as a tool to quantitatively define these concepts. Topics to be discussed include the measures, which quantitatively define component R&M, the relationship between R&M, and the prediction of R&M measures.  

## Course Objectives

Upon completion of this course each student shall be able to:

-	Understand and apply the fundamentals of the concepts of reliability, maintainability, and availability.

- Understand the use of probability theory to quantify R&M concepts.

- Understand and apply the measures which quantitatively define component R&M.
 
## Academic Integrity

Students found to be cheating will be referred for disciplinary action.  Cheating includes, but is not limited to, copying on exams, plagiarizing material from published sources, plagiarizing from former or current AFIT students, submitting someone else’s work as your own, or helping other students to cheat.  If you have any questions regarding what is permissible, please contact the professor for guidance.

## Course Format

Class material is primarily presented in lecture format.   Lecture slides, homework, and other material will be posted on Blackboard.  

## Performance Evaluation

Your grade in this course will be calculated according to the following requirements and their respective weights.

- __HOMEWORK (40\%):__\newline Homework is due at the beginning of class on the day listed in the class schedule.   Each student must turn in their own solutions for each problem assigned.  Solutions will be posted to Blackboard that evening.

- __PROJECT (30\%):__  \newline Students, in teams of two, will prepare a class presentation on a topic relevant to reliability, maintainability, and availability.  Presentations should be about 20 minutes long.  Students may choose a relevant DoD topic or their own topic, approved by the professor.  Topics and teams are "first-come, first-served"  Topic presentations will include the topic's background and why it is important or relevant, a brief literature review of the research on this topic, a description and assessment of any quantitative reliability tools used, and a managerial assessment of why USAF leaders should know and care about it.  

> Project examples: You might perform an evaluation of the C-5 re-engining and reliability improvement program, a B-52 life extension program, F-35 software reliability, or a commercial sector scenario like the recent GM ignition switch or automotive air bag issues.

- __FINAL EXAM (30\%):__  \newline The final exam will test comprehension of the course material in the book and class presentations, and ability to solve mathematic problems scoped similar to the homework.  The exam is closed book, closed notes.  Students may prepare a formula sheet, on 8 ½" x 11" paper, and use both the front and back.  Students will have three hours to finish the exam.
 
Final grades will be based on the following scale

\begin{tabbing}
\=93\;\; \=-\;\; \=100\%\;\;  \=   A\\
\>90\;\; \>-\;\; \>92\%\;\; \> A-\\
\>87\;\; \>-\;\; \>89\%\;\; \>  B+\\
\>83\;\; \>-\;\; \>86\%\;\; \>  B\\
\>80\;\; \>-\;\; \>82\%\;\; \>  B-\\
\>77\;\; \>-\;\; \>79\%\;\; \>  C+\\
\>73\;\; \>-\;\; \>76\%\;\; \>  C\\
\>70\;\; \>-\;\; \>72\%\;\; \>  C-\\
\>       \><\;\;\; \>70\%\;\; \> D or F
\end{tabbing}

## Class Schedule

\begin{tabbing}
\textbf{Class Date}\hspace{20pt}  \=\textbf{Chapters Covered}\hspace{20pt} \=\textbf{Topics}\hspace{120pt} \=\textbf{Notes}\\
Day 2 \> Chapters 1 \& 2     \> Reliability Introduction        \>\\
      \>                     \> Math Review                     \>\\
      \> \> \> \\
Day 3 \> Chapters 3, 4       \> Life Data Analysis              \>HW \#1 Assigned\\
      \>                     \> Monte Carlo Simulation          \>\\
      \> \> \> \\
Day 4 \> Chapters 6          \> Reliability Prediction          \>HW \#1 Due\\
      \>                     \>                                 \>HW \#2 Assigned\\
      \> \> \> \\
Day 5 \> Chapters 12, 14     \> Reliability Testing             \>HW \#2 Due\\
      \>                     \> Reliability Demonstration       \>HW \#3 Assigned\\
      \>                     \> Reliability Growth              \>Project Topics Due\\
      \> \> \> \\
Day 6 \> Chapters 7, 8       \> Design for Reliability          \>HW \#3 Due\\
      \>                     \> Mechanical Systems Reliability  \>HW \#4 Assigned\\
      \> \> \> \\
Day 7 \> Chapters 9, 10      \> Electronic Systems Reliability  \>HW \#4 Due\\
      \>                     \> Software Reliability            \> \\
      \>\>\>\\
Day 8 \> Chapters 15, 16, 17 \> Reliability in Manufacture      \>\\
      \>                     \> Maintainability \& Availability \>\\
      \>                     \> Reliability Management          \>\\
      \> \>\> \\
Day 9 \> N/A                 \>N/A                              \>Student Presentations\\
      \>                     \>                                 \>Review For Final\\
      \> \>\>\\
Day 10\> N/A                 \>N/A                              \>Final Exam\\
\end{tabbing}

## Useful Reliabilty  Websites

The Reliability Information Analysis Center (RIAC)

- __<https://www.quanterion.com/projects/reliability-information-analysis-center-riac/>__

Weibull.com

- Website devoted entirely to the topic of reliability engineering, reliability theory and reliability data analysis and modeling

- __<http://www.weibull.com/knowledge/links.htm>__
